modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#logoFile="examplemod.png"
authors = "${mod_author}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
required = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
